import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { apiRequest, type Screening, type Trial } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { approvedVersions } from './screeningHelpers'

const PATIENT_LIMIT = 50; const TRIAL_LIMIT = 10; const PAIR_LIMIT = 500
export function BatchScreeningPage() {
  const { token } = useAuth(); const navigate = useNavigate(); const [history, setHistory] = useState<Screening[]>([]); const [trials, setTrials] = useState<Trial[]>([]); const [snapshots, setSnapshots] = useState<string[]>([]); const [versions, setVersions] = useState<string[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { try { const [saved, protocols] = await Promise.all([apiRequest<Screening[]>('/screenings', {}, token), apiRequest<Trial[]>('/trials', {}, token)]); setHistory(saved); setTrials(protocols) } catch { setError('Batch screening inputs could not be loaded.') } }, [token]); useEffect(() => { void load() }, [load])
  const uniqueSnapshots = useMemo(() => [...new Map(history.map((item) => [item.patient_snapshot_id, item.patient_snapshot])).entries()], [history]); const approved = approvedVersions(trials); const pairCount = snapshots.length * versions.length; const blocked = !snapshots.length || !versions.length || snapshots.length > PATIENT_LIMIT || versions.length > TRIAL_LIMIT || pairCount > PAIR_LIMIT
  const toggle = (id: string, selected: string[], set: (items: string[]) => void) => set(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (blocked) { setError('Select at least one snapshot and approved version within the configured limits.'); return } setSaving(true); try { const batch = await apiRequest<{ id: string }>('/screening-batches', { method: 'POST', body: JSON.stringify({ patient_snapshot_ids: snapshots, trial_version_ids: versions }) }, token); navigate(`/batches/${batch.id}`) } catch { setError('The batch could not be created. No partial results were saved.') } finally { setSaving(false) } }
  return <section className="route-entry workspace-page"><Link className="back-link" to="/screenings">← Screening history</Link><header className="page-heading"><div><p className="eyebrow">Bounded batch</p><h1>Compare immutable snapshots</h1><p>Every selected pair runs the exact same deterministic single-screening operation.</p></div></header><form onSubmit={submit}><div className="batch-picker"><fieldset><legend>Patient snapshots</legend>{uniqueSnapshots.length ? uniqueSnapshots.map(([id, snapshot]) => <label className="check-row" key={id}><input type="checkbox" checked={snapshots.includes(id)} onChange={() => toggle(id, snapshots, setSnapshots)} /><span><strong>{snapshot?.display_name ?? 'Synthetic patient'}</strong><small>{snapshot?.external_id ?? 'Immutable snapshot'}</small></span></label>) : <div className="empty-state"><p>Run a single screening first to create an immutable patient snapshot.</p></div>}</fieldset><fieldset><legend>Approved trial versions</legend>{approved.length ? approved.map(({ trial, version }) => <label className="check-row" key={version.id}><input type="checkbox" checked={versions.includes(version.id)} onChange={() => toggle(version.id, versions, setVersions)} /><span><strong>{trial.title}</strong><small>{trial.registry_id} · version {version.version}</small></span></label>) : <div className="empty-state"><p>Approve a trial version before adding it to a batch.</p></div>}</fieldset></div><div className={`pair-preview ${pairCount > PAIR_LIMIT ? 'pair-warning' : ''}`}><strong>{pairCount} screening pair{pairCount === 1 ? '' : 's'}</strong><span>Limit: {PATIENT_LIMIT} snapshots × {TRIAL_LIMIT} versions, up to {PAIR_LIMIT} pairs.</span></div>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={blocked || saving} type="submit">{saving ? 'Running batch…' : 'Run batch screening'}</button></form></section>
}
