import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { apiRequest, type Patient, type Trial } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { approvedVersions } from './screeningHelpers'

export function NewScreeningPage() {
  const { token } = useAuth(); const navigate = useNavigate(); const [patients, setPatients] = useState<Patient[]>([]); const [trials, setTrials] = useState<Trial[]>([]); const [patientId, setPatientId] = useState(''); const [versionId, setVersionId] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { try { const [p, t] = await Promise.all([apiRequest<Patient[]>('/patients', {}, token), apiRequest<Trial[]>('/trials', {}, token)]); setPatients(p); setTrials(t); setPatientId(p[0]?.id ?? ''); setVersionId(approvedVersions(t)[0]?.version.id ?? '') } catch { setError('Screening inputs could not be loaded.') } }, [token])
  useEffect(() => { void load() }, [load]); const versions = approvedVersions(trials)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!patientId || !versionId) { setError('Select a patient and an approved trial version.'); return } setSaving(true); try { const result = await apiRequest<{ id: string }>('/screenings', { method: 'POST', body: JSON.stringify({ patient_id: patientId, trial_version_id: versionId }) }, token); navigate(`/screenings/${result.id}`) } catch { setError('The screening could not be run. Review the selected inputs and try again.') } finally { setSaving(false) } }
  return <section className="route-entry workspace-page narrow-page"><Link className="back-link" to="/screenings">← Screening history</Link><header className="page-heading"><p className="eyebrow">Single screening</p><h1>Run an evidence-backed comparison</h1><p>A new immutable patient snapshot is created before the approved trial version is evaluated.</p></header><form className="screening-form" onSubmit={submit}><label>Patient<select value={patientId} onChange={(e) => setPatientId(e.target.value)} required><option value="">Select a patient</option>{patients.map((item) => <option value={item.id} key={item.id}>{item.external_id} · {item.display_name}</option>)}</select></label><label>Approved trial version<select value={versionId} onChange={(e) => setVersionId(e.target.value)} required><option value="">Select an approved version</option>{versions.map(({ trial, version }) => <option value={version.id} key={version.id}>{trial.registry_id} · {trial.title} (v{version.version})</option>)}</select></label>{!patients.length || !versions.length ? <div className="empty-state"><p>You need at least one patient and one approved trial version. <Link to="/patients">Add a patient</Link> or <Link to="/trials">review trial versions</Link>.</p></div> : null}{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={saving || !patients.length || !versions.length} type="submit">{saving ? 'Running screening…' : 'Run screening'}</button></form></section>
}
